#pragma once

void test_getArchiveCatalogueNumber_validArchive_ArchiveCatalogueNumber();
void test_getStateOfDeterioration_validArchive_StateOfDeterioration();
void test_getFileType_validArchive_FileType();
void test_getYearOfCreation_YearOfCreation();
void test_createCopyArchive_validArchive_anotherArchiveWithSameAttributes();
void test_operationGetArchiveRedo_validOperation_ArchiveRedo();
void test_operationGetArchiveUndo_validOperation_ArchiveUndo();
void test_operationGetStringOperation_validOperation_StringOperation();
void test_resizeArray_validArrayToResize_return0();
void test_existArchiveArray_validArchive_return1();
void test_existArchiveArray_invalidArchive_return0();
void test_getPositionArchive_validArchive_position();
void test_getSizeArray_validArrayOfSize2_size2();
void test_repositoryAddArchive_validArchive_return1();
void test_repositoryAddArchive_duplicatedArchive_return0();
void test_repositoryUpdateArchive_validArchive_return1();
void test_repositoryUpdateArchive_invalidArchive_return0();
void test_serviceAddArchive_validArchive_return1();
void test_serviceAddArchive_duplicatedArchive_return0();
void test_serviceDeleteArchive_validArchive_return1();
void test_serviceDeleteArchive_inexistentArchive_return0();
void test_serviceUndo_validUndo_return1();
void test_serviceUndo_invalidUndo_return0();
void test_serviceRedo_validRedo_return1();
void test_serviceRedo_invalidRedo_return0();
void testAll();